import type { ItemDefinition } from "@/lib/types/content";

export const items: Record<string, ItemDefinition> = {
  "yesterdays-bun": {
    id: "yesterdays-bun",
    name: "Yesterday's Bun",
    description: "Baked tomorrow morning. Surprisingly fresh.",
    category: "Food",
    rarity: "common",
    icon: "/art/items/yesterdays-bun.png",
    actionable: "eat",
    tags: ["food", "bakery"],
  },
  "pocket-crumb": {
    id: "pocket-crumb",
    name: "Pocket Crumb",
    description: "Fits nowhere useful. Comforts somehow.",
    category: "Food",
    rarity: "common",
    icon: "/art/items/pocket-crumb.png",
    actionable: "eat",
  },
  "jam-unopened": {
    id: "jam-unopened",
    name: "Jam That Has Not Been Opened Yet",
    description: "The lid remembers a future picnic.",
    category: "Food",
    rarity: "uncommon",
    icon: "/art/items/jam-unopened.png",
    actionable: "eat",
  },
  "backwards-biscuit": {
    id: "backwards-biscuit",
    name: "Backwards Biscuit",
    description: "Crunches before you bite.",
    category: "Food",
    rarity: "common",
    icon: "/art/items/backwards-biscuit.png",
    actionable: "eat",
    tags: ["food"],
  },
  "empty-pie-recipe": {
    id: "empty-pie-recipe",
    name: "Recipe for an Empty Pie",
    description: "Instructions reverse themselves mid-sentence.",
    category: "Curiosities",
    rarity: "rare",
    icon: "/art/items/empty-pie-recipe.png",
    actionable: "inspect",
  },
  "clock-hand": {
    id: "clock-hand",
    name: "Clock Hand",
    description: "Points at almost-now.",
    category: "Curiosities",
    rarity: "uncommon",
    icon: "/art/items/clock-hand.png",
    actionable: "inspect",
  },
  "rewind-token": {
    id: "rewind-token",
    name: "Rewind Token",
    description: "Warm metal. Smells faintly of Tuesday.",
    category: "Curiosities",
    rarity: "rare",
    icon: "/art/items/rewind-token.png",
    actionable: "inspect",
  },
  "tiny-tomorrow": {
    id: "tiny-tomorrow",
    name: "Tiny Tomorrow",
    description: "A marble of unused morning.",
    category: "Curiosities",
    rarity: "legendary",
    icon: "/art/items/tiny-tomorrow.png",
    actionable: "inspect",
  },
  "small-lantern": {
    id: "small-lantern",
    name: "Small Lantern",
    description: "Lights the path you nearly took.",
    category: "Home",
    rarity: "common",
    icon: "/art/items/small-lantern.png",
    price: 20,
    actionable: "place",
  },
  "crooked-rug": {
    id: "crooked-rug",
    name: "Crooked Room Rug",
    description: "Lies flat in every direction but one.",
    category: "Home",
    rarity: "uncommon",
    icon: "/art/items/crooked-rug.png",
    price: 35,
    actionable: "place",
  },
  "button-jar": {
    id: "button-jar",
    name: "Button Jar",
    description: "Spriggle would approve.",
    category: "Curiosities",
    rarity: "common",
    icon: "/art/items/button-jar.png",
    price: 15,
    actionable: "inspect",
  },
  "companion-snack": {
    id: "companion-snack",
    name: "Companion Snack",
    description: "Soft, shared, slightly glowing.",
    category: "Food",
    rarity: "common",
    icon: "/art/items/companion-snack.png",
    price: 12,
    actionable: "eat",
    tags: ["food", "offerable"],
  },
  "town-poster": {
    id: "town-poster",
    name: "Backwards Town Poster",
    description: "The arrow points away from town. On purpose.",
    category: "Home",
    rarity: "common",
    icon: "/art/items/town-poster.png",
    price: 18,
    actionable: "place",
  },
  "clockwork-hat": {
    id: "clockwork-hat",
    name: "Clockwork Hat",
    description: "Ticks softly when you think too hard.",
    category: "Clothing",
    rarity: "uncommon",
    icon: "/art/items/clockwork-hat.png",
    price: 40,
    actionable: "wear",
  },
  "empty-map-frame": {
    id: "empty-map-frame",
    name: "Empty Map Frame",
    description: "Waiting for a place that has not noticed you yet.",
    category: "Home",
    rarity: "uncommon",
    icon: "/art/items/empty-map-frame.png",
    price: 28,
    actionable: "place",
  },
  "couriers-rewind-cap": {
    id: "couriers-rewind-cap",
    name: "Courier's Rewind Cap",
    description: "Awarded for surviving backwards streets.",
    category: "Clothing",
    rarity: "rare",
    icon: "/art/items/couriers-rewind-cap.png",
    actionable: "wear",
  },
  "moon-fragment": {
    id: "moon-fragment",
    name: "Moon Fragment",
    description: "Cool stone that remembers an eye of light.",
    category: "Quest",
    rarity: "legendary",
    icon: "/art/items/moon-fragment.png",
    actionable: "inspect",
  },
  "unbaked-loaf": {
    id: "unbaked-loaf",
    name: "Unbaked Loaf",
    description: "Already smells finished. Mara insists it is not.",
    category: "Quest",
    rarity: "uncommon",
    icon: "/art/items/unbaked-loaf.png",
    actionable: "inspect",
  },
};

export const itemList = Object.values(items);
